server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybase?serverTimezone=Asia/Shanghai&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: xsp888
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
#    static-path-pattern: /**
#    resources:
#      static-locations: classpath:/static/
    thymeleaf:
#    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
#    mode: HTML
#    #编码 可不用配置
#    encoding: UTF-8
#    servlet:
#      #内容类别,可不用配置
#      content-type: text/html
#    #开发配置为false,避免修改模板还要重启服务器
      cache: false
#    #配置模板路径，默认是templates，可以不用配置
#    prefix: classpath:/templates
#    suffix: .html
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 30000
mybatis:
  #config-locations: classpath:conf/mybatis-config.xml
  mapper-locations: classpath:conf/mapper/*.xml
  #type-aliases-package: com.example.demo.mapper.*
  


  
  
